### ISSUE TITLE
rkinstall is not accessible

### ISSUE THREAD

**Issue by Albedo001** [fire219/sadie#5]
Hi,

from my place (China), with or withour VPN, I cannot access to rkinstall with the wget command in SADIE

"fire219.kotori.me/sadie/rkinstall" is not accessible

thanks

**Comment by fire219** [comment]
It is not a problem with your connection. The kotori.me server is currently down. I don't know when it might be back up, as that is somewhat out of my control.

I'm also hesitant to update SADIE to use a new download location, as it is now redundant. [There are now R64 Android builds which do not require rkinstall, which means SADIE isn't needed.](http://wiki.pine64.org/index.php/ROCK64_Software_Release#Android_8.x_eMMC)
